# Generated by Django 5.0.1 on 2024-02-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_profile_pic2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_gallery',
            name='picture',
            field=models.ImageField(upload_to='profile/gallery'),
        ),
    ]
